server:
  port: 8206
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?useSSL=false
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss   # json的全局时间格式
    time-zone: GMT+8
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb://42.192.9.219:39134/yygh_hosp
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos服务地址
#  redis:
#    host: 42.192.9.219
#    port: 7537
#    password: lyx_dt985_07lj
#    lettuce:
#      pool:
#        max-idle: 5
#        min-idle: 0
  rabbitmq:
    host: 42.192.9.219
    port: 5672
    username: guest
    password: guest
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl