server:
  port: 8205
spring:
  application:
    name: service-oss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss   # json的全局时间格式
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tCkTVdXDyyuEzVmK1eV
    secret: VmWzRehgz1uG9iSg4EX81PR40Rwmcu
    bucket: yygh-lcxy