server:
  port: 8207
spring:
  application:
    name: service-task
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos服务地址
  rabbitmq:
    host: 42.192.9.219
    port: 5672
    username: guest
    password: guest